CREATE DATABASE YAHTZEE;

CREATE USER 'YAHTZEE_DBA'@'localhost' IDENTIFIED BY 'root123';

GRANT ALL PRIVILEGES ON YAHTZEE.* TO 'YAHTZEE_DBA'@'localhost';

FLUSH PRIVILEGES;

CREATE TABLE YAHTZEE.USUARIOS (
    USUARIO VARCHAR(10) PRIMARY KEY,
    CONTRASENA VARCHAR(32),
    VICTORIAS INT,
    DERROTAS INT
);

INSERT YAHTZEE.USUARIOS VALUES ('Aguilar', MD5('PASSWORD'), 0, 0);

COMMIT;